version: 0.1
phases:
  install:
    commands:
      - sudo npm install
      - sudo npm install --only=dev
      - aws configure set preview.cloudfront true
  build:
    commands:
      - sudo ./node_modules/.bin/react-scripts build
  post_build:
    commands:
      - aws s3 sync --delete --exclude static/* build/ "s3://${BUCKET_NAME}"
      - aws s3 sync --delete --cache-control "max-age=31536000" build/static "s3://${BUCKET_NAME}/static"
      - aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths /\*